enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
archive-dlurl = "https://archive.org/download/revanced-files/apks/com.google.android.youtube"

[YouTubeMusic]
app-name = "YouTube Music"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/revanced-files/apks/com.google.android.apps.youtube.music"

[TikTok]
app-name = "TikTok"
archive-dlurl = "https://archive.org/download/revanced-files/apks/com.ss.android.ugc.trill"
included-patches = "'SIM spoof'"
