name: Test Discord
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Send a message with multiple component
        uses: MineBartekSA/discord-webhook@v2
        with:
          webhook: ${{ secrets.APPLICATION_WEBHOOK }}
          content: Some text
          component: |
            - type: 2
              style: 5
              label: Link Button
              url: https://google.com/
            - type: 2
              style: 5
              label: Second Link Button
              url: https://github.com/
              
