name: test build
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:          
      - name: Report to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: env.DISCORD_WEBHOOK != null
        run: |
          echo '{
            "content": "**New build!**\n**▼ Downloads:**\n📦 youtube-music-revanced-v8.31.51-arm64-v8a.apk\n📦 another-app.apk\n📦 third-app.apk\n",
            "username": "ReVanced",
            "avatar_url": "https://i.imgur.com/epsOc0q.png",
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "youtube-music-revanced-v8.31.51-arm64-v8a.apk",
                    "url": "https://github.com/Auris007/rev-files/releases/download/68/youtube-music-revanced-v8.31.51-arm64-v8a.apk"
                  },
                  {
                    "type": 2,
                    "style": 5,
                    "label": "another-app.apk",
                    "url": "https://github.com/Auris007/rev-files/releases/download/68/another-app.apk"
                  },
                  {
                    "type": 2,
                    "style": 5,
                    "label": "third-app.apk",
                    "url": "https://github.com/Auris007/rev-files/releases/download/68/third-app.apk"
                  }
                ]
              }
            ]
          }' > test_payload.json
          curl -H "Content-Type: application/json; charset=utf-8" \
               -H "User-Agent: curl/8.5.0" \
               -H "Accept: */*" \
               -d @test_payload.json \
               -v \
               https://discord.com/api/webhooks/${DISCORD_WEBHOOK}?with_components=true
